blank_issues_enabled: false
contact_links:
  - name: Documentation issue
    url: https://plum330.dev/en/docs/
    about: For documentation issues, open a pull request at the plum330/plum330.dev repository
